### PR TITLE
5.1.12

### PR DESCRIPTION
**Pull request by nrandon**

### CODE REVIEW

**Comment by nrandon** [comment]
@ryecoaaron can you build 5.1.12 as it should be ready to go

**Comment by ryecoaaron** [comment]
Ok.  I will do that.  Do you want me to build the package as soon as you merge the PR from now on?

**Comment by nrandon** [comment]
Better not as it take me time to check it sometime its best to prompt you when it ready @ryecoaaron if that is ok ?

**Comment by ryecoaaron** [comment]
that is fine with me too.  5.1.12 is in the repo.

**Comment by nrandon** [comment]
thanks

**Pull request merged**
