### PR TITLE
Porting of AutoShutdown to OMV 6.x

### PR DESCRIPTION
**Pull request by nrandon**
Changes required for new OMV 6.x GUI and script improvements

### CODE REVIEW

**Comment by nrandon** [comment]
@ryecoaaron The porting of AutoShutdown to OMV 6.x is done can you build it and add it the the repo. Thanks

**Comment by nrandon** [comment]
@ryecoaaron it will also need the local re-doing

**Comment by ryecoaaron** [comment]
In the repo now.  We will have to look at how to do hints since multiline translations don't work with transifex.  Each line will probably have to be a translated string that are concatenated together in the yaml.

**Comment by nrandon** [comment]
@ryecoaaron Is there a way i can run transifex directly so I can see if i can fix this ?

**Comment by ryecoaaron** [comment]
Yes but now that I look at the code, I need to update my locale generation too.   Here is how Volker is doing it - https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault.mk#L45

**Comment by ryecoaaron** [comment]
I was able to update the code and fix the multi-line support.  Locales have been updated in the latest commit.

**Comment by nrandon** [comment]
@ryecoaaron something still not correct here as some of the text is missing in the pot file. I got a 6.0.1 patch on the way to address the issues with the hint and xgettext should work with it now.

**Pull request merged**
