### PR TITLE
5.1.16

### PR DESCRIPTION
**Pull request by nrandon**

### CODE REVIEW

**Comment by ryecoaaron** [comment]
Should I deprecate the wakealarm plugin with this new functionality?

**Comment by nrandon** [comment]
@ryecoaaron let no do that yet I think there is more than one use case. Also let check no one find a problem with this

**Comment by nrandon** [comment]
@ryecoaaron It ready to build I do all the testing I can think of (bet I missed something).

**Comment by ryecoaaron** [comment]
In the repo now.

**Pull request merged**
