### PR TITLE
Add transsmission download monitor

### PR DESCRIPTION
**Pull request by partizand**
Hi!
I know that such do not like. But I added monitoring that the transmission downloads torrents.
Tested only that when there are no downloads, the computer turns off. Actions during download is not tested.
I did not make the package, I updated the plug-in files manually.
Dependence on the transmission-cli package appeared.
Authorization transmission is not used, but can be easily added.
OMV4 Arrakis, debian 9 strech

### CODE REVIEW

**Comment by subzero79** [comment]
My opinion is this should be implemented in a more generic way. The current autoshutdown plugin scheme [checks on file existence and contents](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/713ebb2d0bed963b9cdedb0d51ffb0c3ca1f2d6b/README/README_for_script#L125) 

So if you ask me maybe implement also script execution, so if we add a scripts to autoshutdown-scripts.d/ folder then don't turn off if exit code is different than zero or similar. People can contribute scripts to be shipped with the plugin as PR then somehow users will have to activate them by naming them explicitly in the extra options or add their customs.

We can work this together if you want in the next few days. I haven't created any plugins from scratch but i have contributed several PR's for core and omvextras so i have no problem in using existing code.

Just my comment, let me know what you think.

**Comment by partizand** [comment]
I like your idea. Good way, it will be universal.

Just need a simple web interface for scripts and files.
It will be hard for ordinary users with the current interface :)

Autoshutdown is a script that can be fully decomposed into user scripts :)
Perhaps you need to leave the basic things and use them in the core.

I saw the monitoring of the files, but this is not enough for transmission. If there would be running scripts, I would have enough.

Sorry, there's no way to help with development now. Perhaps in January there will be time. I turned off my Omv for not having hdd

**Comment by ryecoaaron** [comment]
A few things...

You need to add a migration script to add this new database field to an existing install of autoshutdown.  Otherwise, getSettings will fail to validate.

I don't like add transmission-cli as a dependency of the plugin.  Not every user of autoshutdown wants transmission installed on their system.  The script should just do the right thing if the transmission monitoring is enable AND transmission is installed.  I guess if you wanted to do it completely right, you could disable the transmission fields in the plugin if transmission wasn't installed.

I like subzero's idea of using run parts directory.  Like partizand said, maybe that would be a good time to break the autoshutdown script itself in parts.

**Comment by partizand** [comment]
You're right, I'll try to remove the dependence on transmission-cli
Is there a link to the documentation or sample how to add a field to the database?

Dependency, I also do not like, but to determine if the transmission is installed I can not. In addition, transmission is not set by default with a transmission-cli dependency

OK. add in the plug-ins run scripts without an interface. For me it will be enough.

**Comment by ryecoaaron** [comment]
Here is a migration script that will add a field - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-letsencrypt/blob/master/usr/share/openmediavault/confdb/migrations.d/conf.service.letsencrypt_3.4.2.sh

It is very easy to determine if transmission is installed.  You can either check if the binary is install with:
if [ -f /usr/bin/transmission-cli ]; then
or you could check to see if the package is installed:
if dpkg -l transmission-cli >/dev/null 2.&1; then

Whether transmission is set by default is not the problem.  I would not want it on my system at all.

**Comment by partizand** [comment]
ok, I'll fix it

**Comment by partizand** [comment]
It is wrong, close

**Pull request closed without merging**
