### PR TITLE
6.0.1

### PR DESCRIPTION
**Pull request by nrandon**
address some yaml and translation issues

### CODE REVIEW

**Comment by nrandon** [comment]
@ryecoaaron Can you test this before this before it is merged and see if it now works correctly produce the translation file (it did in my testing, but what to make sure). If is does work then it can be merged and built. If it fails let me know and I will look in to it further and see what else I can do. thanks :)

**Comment by ryecoaaron** [comment]
It looks fine to me and the generated locale file looks good.

**Comment by nrandon** [comment]
@ryecoaaron thanks so it ready for release

**Comment by ryecoaaron** [comment]
In the repo now.

**Pull request merged**
