### PR TITLE
fix load average check

### PR DESCRIPTION
**Pull request by BenBipod**
Load average check could not determine current load correctly to the effect that the load threshold was never seen to be reached and therefore no actual load ever stopped the system from doing an auto shutdown. The bug was introduced two years ago in an attempt to deal with localization variants of the `top` command output (decimal point vs. comma), which instead broke processing for all locales.

This addresses parts of #47.

Debug log from a successful test run in German locale: [autoshutdown_load_test.log](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/2442087/autoshutdown_load_test.log)

### CODE REVIEW

**Comment by erdnussflips** [comment]
@ryecoaaron ?

**Comment by ryecoaaron** [comment]
@BenBipod @erdnussflips I have no way to test this.  So, I don't like blindly accepting pull requests.

I'm also not sure why top is being used since it is an interactive program.  /proc/loadavg seems like a much better option to me.
instead of:
```
# grab first line, with the load averages; use C-locale to avoid internationalization issues
CURRENT_LOAD_AVERAGE_LINE=$(LC_ALL=C top -b -n 1 | head -1)
# grab first value, with the one-minute load average in decimal notation
CURRENT_LOAD_AVERAGE_DECIMAL=$(echo $CURRENT_LOAD_AVERAGE_LINE | sed -E 's/.*load average: ([0-9.]+).*/\1/')
```
just do (avoids C-locale as well):
```
# grab first value, with the one-minute load average in decimal notation
CURRENT_LOAD_AVERAGE_DECIMAL=$(awk '{print $1}' /proc/loadavg)
```

**Comment by BenBipod** [comment]
So can we do anything to make this testable for you?
Regarding top, that is what was used before, and I tried to keep the fix small and easy to review. When given the -b option (for batch) it is, in fact, non-interactive.

**Comment by ryecoaaron** [comment]
@BenBipod Not really.  I use VMs and they don't behave in the same way hardware does.  I have never used this plugin either.  Even a second person saying the pull request worked would be enough.

I didn't see the -b flag but it is still gross to parse the output of top.  I wasn't blaming you for using it. 
 Fixes don't have to be small if they make it better :)  Every time I have fixed it, I want to change LOTS of it lol

**Comment by BenBipod** [comment]
@erdnussflips, as you seemed interested: Would you maybe care to test the patch and report back here? As @ryecoaaron said, that might be enough for it to get going.

**Comment by chuba144** [comment]
Had the same problem, tried out @BenBipod's modification, works like a charm.

**Pull request merged**
