### PR TITLE
Fix logging regression

### PR DESCRIPTION
**Pull request by nrandon**
Logging is not working correctly in the new package and log are
going to messages. This change fixed the rsyslog config to correct
the issue.

### CODE REVIEW

**Comment by nrandon** [comment]
@ryecoaaron found a bug in the logging can this be pushed up (sorry for the mistake)

**Comment by ryecoaaron** [comment]
Before or after the merge?

**Comment by nrandon** [comment]
This fixes the regression I introduced in the last build. can a new build be made with this new fix ?

**Comment by ryecoaaron** [comment]
sure.

**Comment by ryecoaaron** [comment]
5.0.6 in the repo

**Pull request merged**
