### PR TITLE
Added the ability to use scripts, which can check if something needs to pervent the shutdown

### PR DESCRIPTION
**Pull request by erdnussflips**
I don't have the facility to do a complete integration test.
Maybe one reviewer can do that?

### CODE REVIEW

**Comment by ryecoaaron** [comment]
As with the other pull request, I have no way to test this.  It is also a little disappointing that functionality is only added to the script and not to the plugin itself.

**Comment by ErdnussFlipS** [comment]
@ryecoaaron Can you tell me, what I need to do, to build the package? Then I can test this on my omv instance.

**Comment by ryecoaaron** [comment]
Installing these packages should be enough: debhelper, devscripts, fakeroot, build-essential

Then from the root of the downloaded code from git:  fakeroot debian/rules clean binary

The code has to be on a filesystem that is mounted executable.  So, a data drive mounted by OMV will not work since they are mounted noexec.

**Comment by ErdnussFlipS** [comment]
Updated package file
[openmediavault-autoshutdown_4.0.3_all.deb.zip](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/1877581/openmediavault-autoshutdown_4.0.3_all.deb.zip)

**Comment by ErdnussFlipS** [comment]
@ryecoaaron I fixed some stuff and added an example plugin. Do you want to review my changes?

[openmediavault-autoshutdown_4.0.3_all.deb.zip](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/1887926/openmediavault-autoshutdown_4.0.3_all.deb.zip)

**Comment by ErdnussFlipS** [comment]
I need to fix some more stuff for the log.

**Comment by ErdnussFlipS** [comment]
Ok, I fixed the log stuff. Now the log of one script plugin is written correctly into autoshutdown's log

**Comment by nrandon** [comment]
conflict in merge now so will close re-open if fixed

**Pull request closed without merging**
