### PR TITLE
Add support for ipv4-mapped ipv6 address in port check

### PR DESCRIPTION
**Pull request by nrandon**
Add support for ipv4-mapped ipv6 address as the 'ss -n' command will
display the ipv4-mapped address as '[::ffff:<ipv4 address]:<port>'
rather than just an ipv4 address. Also in such an instance the
connection addresses will be similarly formatted and must be adjusted.

Additionally cleanup connection output so all of the ipv4 connection
addresses are presented for a port.

### CODE REVIEW

**Comment by ryecoaaron** [comment]
@nrandon Sorry but if you look at the other pull requests for this plugin, I am the worst one to merge or review this.  There is a lot of behavior changing that I can't test.  I wish someone else would maintain this plugin who actually uses it.

**Comment by nrandon** [comment]
@ryecoaaron is there anyone that can review this, as caring the change locally is not a grate solution ?

**Comment by nrandon** [comment]
not ment to close

**Comment by ryecoaaron** [comment]
@nrandon I would ask on the forum.  I'm not sure who could review it.

**Comment by FernetMenta** [comment]
I tested this change and I think it is correct.

Output of ss -n | grep ESTAB
```
tcp  ESTAB  0   0  [::ffff:192.168.178.25]:80          [::ffff:192.168.178.53]:52845
```

The new regex:
```
ss -n | awk -v regex="^([[]::ffff:)?192.168.178.25[]]?:80$" '$2 ~ /^ESTAB$/ && $5 ~ regex'
```

catches this:
```
tcp               ESTAB                  0                   0                                                                          [::ffff:192.168.178.25]:80                                        [::ffff:192.168.178.53]:52845         
tcp               ESTAB                  0                   0                                                                          [::ffff:192.168.178.25]:80                                        [::ffff:192.168.178.53]:52844 
```

The old one does not and is useless with debian buster even if ipv6 is disabled

**Comment by FernetMenta** [comment]
fixes https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/issues/67

**Comment by nrandon** [comment]
@ryecoaaron now this has been reviewed and tested independently can it be merged ?

**Pull request merged**
